AWSTemplateFormatVersion: '2010-09-09'
Description: Parent stack to manage nested stacks

Parameters:
  S3Bucket:
    Type: String
  LambdaS3Bucket:
    Type: String
  LambdaS3Key:
    Type: String
  AgentResourceRoleArn:
    Type: String
  CustomerEncryptionKeyArn:
    Type: String
  FoundationModel:
    Type: String

Resources:
  S3AndLambdaStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 'https://${S3Bucket}/s3-and-lambda-template.yaml'
      Parameters:
        LambdaS3Bucket: !Ref LambdaS3Bucket
        LambdaS3Key: !Ref LambdaS3Key

  AthenaStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 'https://${S3Bucket}/athena-template.yaml'
      Parameters:
        S3Bucket: !Ref S3Bucket
    DependsOn: S3AndLambdaStack

  BedrockAgentStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 'https://${S3Bucket}/bedrock-agent-template.yaml'
      Parameters:
        AgentResourceRoleArn: !Ref AgentResourceRoleArn
        CustomerEncryptionKeyArn: !Ref CustomerEncryptionKeyArn
        FoundationModel: !Ref FoundationModel
    DependsOn: AthenaStack

Outputs:
  S3BucketName:
    Description: 'Name of the S3 bucket created'
    Value: !GetAtt S3AndLambdaStack.Outputs.S3BucketName
  LambdaFunctionName:
    Description: 'Name of the Lambda function created'
    Value: !GetAtt S3AndLambdaStack.Outputs.LambdaFunctionName
  AthenaDatabaseName:
    Description: 'Name of the Athena database created'
    Value: !GetAtt AthenaStack.Outputs.AthenaDatabaseName
  BedrockAgentName:
    Description: 'Name of the Bedrock Agent created'
    Value: !GetAtt BedrockAgentStack.Outputs.BedrockAgentName
  BedrockAgentArn:
    Description: 'ARN of the Bedrock Agent created'
    Value: !GetAtt BedrockAgentStack.Outputs.BedrockAgentArn
